# Table processing notebook

### It creates a new column to the pfam table wich contains the name ofthe gene (e.g. ABL1 or SYK)

In [1]:
import pandas as pd

In [3]:
basedir = "/sh2db_vagrant/SH2db/shared/data/"

In [18]:
pfam = pd.read_csv(basedir+'pfam_table_recalculated_0830.csv')
pfam.drop(['Unnamed: 0'], 'columns', inplace = True)
pfam

,UniProt entry,Gene_domain,Pole,UniProt residues,PDB ID,PDB chain ID,PDB residues,Category,Gene name,Species,...,Res_stop,Uniprot_ID,New_uniprot_start,New_uniprot_stop,Old_uniprot_start,Old_uniprot_stop,diff_start,New_PDB_start,diff_stop,New_PDB_stop
0,3BP2_HUMAN,SH3BP2,N,458 - 538,2CR4,A,20 - 100,SigReg,SH3BP2,HUMAN,...,100,P78314,435,561,458,538,23,0,23,123
1,ABL1_HUMAN,ABL1,N,127 - 202,1AB2,A,11 - 86,Kinases,ABL1,HUMAN,...,86,P00519,105,228,127,202,22,0,26,112
2,ABL1_HUMAN,ABL1,N,127 - 202,1OPL,A,146 - 221,Kinases,ABL1,HUMAN,...,221,P00519,105,228,127,202,22,124,26,247
3,ABL1_HUMAN,ABL1,N,127 - 202,1OPL,B,146 - 221,Kinases,ABL1,HUMAN,...,221,P00519,105,228,127,202,22,124,26,247
4,ABL1_HUMAN,ABL1,N,127 - 202,2ABL,A,146 - 221,Kinases,ABL1,HUMAN,...,221,P00519,105,228,127,202,22,124,26,247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,ZAP70_HUMAN,ZAP70_C,C,163 - 239,1M61,A,163 - 239,Kinases,ZAP70,HUMAN,...,239,P43403,148,265,163,239,15,148,26,265
636,ZAP70_HUMAN,ZAP70_C,C,164 - 239,2OQ1,A,165 - 241,Kinases,ZAP70,HUMAN,...,241,P43403,148,265,164,239,16,149,26,267
637,ZAP70_HUMAN,ZAP70_C,C,165 - 239,2OZO,A,163 - 239,Kinases,ZAP70,HUMAN,...,239,P43403,148,265,165,239,17,146,26,265
638,ZAP70_HUMAN,ZAP70_C,C,167 - 239,4XZ0,A,163 - 239,Kinases,ZAP70,HUMAN,...,239,P43403,148,265,167,239,19,144,26,265
639,ZAP70_HUMAN,ZAP70_C,C,168 - 239,4XZ1,A,163 - 239,Kinases,ZAP70,HUMAN,...,239,P43403,148,265,168,239,20,143,26,265

In [19]:
pfam_gene_col = pfam["UniProt entry"].str.split('_', expand = True)

In [20]:
pfam_gene_col = pfam_gene_col[0]

In [21]:
pfam_gene_col

0       3BP2
1       ABL1
2       ABL1
3       ABL1
4       ABL1
       ...
635    ZAP70
636    ZAP70
637    ZAP70
638    ZAP70
639    ZAP70
Name: 0, Length: 640, dtype: object

In [22]:
pfam.insert(1, "Gene_col", pfam_gene_col, True)

In [23]:
pfam.head()

,UniProt entry,Gene_col,Gene_domain,Pole,UniProt residues,PDB ID,PDB chain ID,PDB residues,Category,Gene name,...,Res_stop,Uniprot_ID,New_uniprot_start,New_uniprot_stop,Old_uniprot_start,Old_uniprot_stop,diff_start,New_PDB_start,diff_stop,New_PDB_stop
0,3BP2_HUMAN,3BP2,SH3BP2,N,458 - 538,2CR4,A,20 - 100,SigReg,SH3BP2,...,100,P78314,435,561,458,538,23,0,23,123
1,ABL1_HUMAN,ABL1,ABL1,N,127 - 202,1AB2,A,11 - 86,Kinases,ABL1,...,86,P00519,105,228,127,202,22,0,26,112
2,ABL1_HUMAN,ABL1,ABL1,N,127 - 202,1OPL,A,146 - 221,Kinases,ABL1,...,221,P00519,105,228,127,202,22,124,26,247
3,ABL1_HUMAN,ABL1,ABL1,N,127 - 202,1OPL,B,146 - 221,Kinases,ABL1,...,221,P00519,105,228,127,202,22,124,26,247
4,ABL1_HUMAN,ABL1,ABL1,N,127 - 202,2ABL,A,146 - 221,Kinases,ABL1,...,221,P00519,105,228,127,202,22,124,26,247

In [25]:
pfam.to_csv('/home/takacsg/Documents/sh2db/data/pfam_table_1017.csv')

## Fill up the empty cells with the (vertically) previous cell's value  of a table:

In [ ]:
table.fillna(method='ffill', inplace = True)

## XLSX to CSV snippet (Dávid):

In [ ]:
df = pd.read_excel('C:\\Users\\David\\Dropbox\\bin\\sh2db\\table_from_alignment_with_pdbs_0917.xlsx', index_col=[0,1])

In [ ]:
df.to_csv('C:\\Users\\David\\Dropbox\\bin\\sh2db\\table_from_alignment_with_pdbs_0917.csv', index=[0,1])